# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.10

# Fabric API
fabric_version=0.102.0+1.21

# Mod Dependencies
fabric_permissions_api_version=0.3.1
# https://github.com/NickImpact/Impactor/tree/1.20.1
impactor_economy_api_version=5.1.1+1.20.1
diamondeconomy_version=1.6.1+1.21
# https://github.com/Patbox/sgui
sgui_version=1.6.0+1.21
# https://github.com/Patbox/polymer
polymer_version=0.9.9+1.21
# https://github.com/Patbox/TextPlaceholderAPI
placeholder_api_version=2.4.1+1.21

common_economy_api_version=1.1.1
cloth_config_version=15.0.127
sqlite_version=3.36.0.3

# Mod Properties
mod_version=1.4.4+1.21
maven_group=rickiewars.guishop
archives_base_name=gui-shop
