# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Silences Stonecutter's Groovy-vs-Kotlin DSL warning.
# Switching to Kotlin DSL is still under consideration.
dev.kikugie.stonecutter.hard_mode=true

# Mod Dependencies
sqlite_version=3.36.0.3

# For Unit Testing
# See the [fabric-loader-unit maven artifacts](https://mvnrepository.com/artifact/net.fabricmc/fabric-loader-junit)
# Select the version that matches the loader version (https://mvnrepository.com/artifact/net.fabricmc/fabric-loader-junit/<loader_version>)
# Check the runtime dependencies for the required platform version
junit_version=5.10.0
junit_platform_version=1.10.0

# Mod Properties
mod_version=2.1.0
maven_group=rickiewars.guishop
archives_base_name=gui-shop
