# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.2
yarn_mappings=1.21.2+build.1
loader_version=0.16.10

# Fabric API
fabric_version=0.106.1+1.21.2

# Mod Dependencies
fabric_permissions_api_version=0.3.2
# https://github.com/Patbox/sgui
sgui_version=1.7.2+1.21.2
# https://github.com/Patbox/polymer
polymer_version=0.10.0+1.21.2
# https://github.com/Patbox/TextPlaceholderAPI
placeholder_api_version=2.5.0+1.21.2

common_economy_api_version=1.1.1
sqlite_version=3.36.0.3

# Mod Properties
mod_version=1.4.10+1.21.2
maven_group=rickiewars.guishop
archives_base_name=gui-shop
