minecraft_version=26.1
java_version=25

# https://github.com/lucko/fabric-permissions-api
fabric_permissions_api_version=0.7.0

# Fabric API
fabric_version=0.145.1+26.1

# Mod Dependencies
# https://github.com/Patbox/sgui
sgui_version=2.0.0+26.1
# https://github.com/Patbox/polymer
polymer_version=0.16.5+26.1.2
# https://github.com/Patbox/TextPlaceholderAPI
placeholder_api_version=3.0.0+26.1
# https://github.com/Patbox/common-economy-api
common_economy_api_version=2.0.0
