minecraft_version=1.21.2
loader_version=0.16.10
loom_version=1.14-+

# https://github.com/lucko/fabric-permissions-api
fabric_permissions_api_version=0.3.3

# Fabric API
fabric_version=0.106.1+1.21.2

# Mod Dependencies
# https://github.com/Patbox/sgui
sgui_version=1.7.2+1.21.2
# https://github.com/Patbox/polymer
polymer_version=0.10.0+1.21.2
# https://github.com/Patbox/TextPlaceholderAPI
placeholder_api_version=2.5.0+1.21.2
# https://github.com/Patbox/common-economy-api
common_economy_api_version=1.1.1
