minecraft_version=26.3-rc-2
# TODO: remove minecraft_version_dependency once 26.3 releases.
minecraft_version_dependency=26.3-rc.2
java_version=25

# https://github.com/lucko/fabric-permissions-api
fabric_permissions_api_version=0.7.0

# Fabric API
fabric_version=0.160.4+26.3

# Mod Dependencies
# https://github.com/Patbox/sgui
sgui_version=2.2.0+26.3
# https://github.com/Patbox/polymer
polymer_version=0.18.0+26.3-rc-1
# https://github.com/Patbox/TextPlaceholderAPI
placeholder_api_version=3.2.0+26.3
# https://github.com/Patbox/common-economy-api
common_economy_api_version=2.0.0
